"""Relational model.

Types are deliberately portable: the same models run on PostgreSQL in
production and on SQLite for local development and tests. JSON columns use
`JSONB` on PostgreSQL through a variant, identifiers are 32 character hex
strings instead of a database specific UUID type, and every timestamp is stored
timezone aware and generated by the application.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime

from sqlalchemy import (
    JSON,
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship
from sqlalchemy.types import TypeDecorator


class UTCDateTime(TypeDecorator):
    """Timestamps that behave the same on PostgreSQL and SQLite.

    SQLite has no timezone aware storage, so values are normalised to UTC on the
    way in and made aware again on the way out. Without this, a comparison such
    as `expires_at < now` silently changes meaning between the two backends.
    """

    impl = DateTime(timezone=True)
    cache_ok = True

    def process_bind_param(self, value: datetime | None, dialect):
        if value is None:
            return None
        if value.tzinfo is None:
            value = value.replace(tzinfo=UTC)
        value = value.astimezone(UTC)
        return value.replace(tzinfo=None) if dialect.name == "sqlite" else value

    def process_result_value(self, value: datetime | None, dialect):
        if value is None:
            return None
        if value.tzinfo is None:
            return value.replace(tzinfo=UTC)
        return value.astimezone(UTC)


#: Project roles, from least to most capable.
ROLE_VIEWER = "viewer"
ROLE_EDITOR = "editor"
ROLE_OWNER = "owner"
ROLES = (ROLE_VIEWER, ROLE_EDITOR, ROLE_OWNER)

#: Where the editorial documents of a project actually live.
MODE_WORKSPACE = "workspace"  # JSON files in the Git checkout (the current video)
MODE_MANAGED = "managed"  # rows in the database (cloud projects)
STORAGE_MODES = (MODE_WORKSPACE, MODE_MANAGED)

JOB_QUEUED = "queued"
JOB_RUNNING = "running"
JOB_SUCCEEDED = "succeeded"
JOB_FAILED = "failed"
JOB_CANCELLED = "cancelled"
JOB_STATUSES = (JOB_QUEUED, JOB_RUNNING, JOB_SUCCEEDED, JOB_FAILED, JOB_CANCELLED)

PROJECT_STATUSES = ("draft", "review", "approved", "published")

JsonColumn = JSON().with_variant(JSONB, "postgresql")


def new_id() -> str:
    return uuid.uuid4().hex


def utcnow() -> datetime:
    return datetime.now(UTC)


class Base(DeclarativeBase):
    pass


class TimestampMixin:
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)
    updated_at: Mapped[datetime] = mapped_column(
        UTCDateTime, default=utcnow, onupdate=utcnow
    )


class User(Base, TimestampMixin):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    #: Stored lowercase; `services.accounts` normalises before every lookup.
    email: Mapped[str] = mapped_column(String(320), unique=True, nullable=False)
    name: Mapped[str] = mapped_column(String(160), nullable=False, default="")
    password_hash: Mapped[str] = mapped_column(String(255), nullable=False, default="")
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, default=True)
    is_admin: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    last_login_at: Mapped[datetime | None] = mapped_column(UTCDateTime)

    memberships: Mapped[list[Membership]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )


class AuthSession(Base):
    """A signed-in browser. Tokens are stored hashed so a database dump cannot
    be replayed as a login."""

    __tablename__ = "auth_sessions"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    user_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    token_hash: Mapped[str] = mapped_column(String(64), unique=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)
    expires_at: Mapped[datetime] = mapped_column(UTCDateTime, nullable=False)
    revoked_at: Mapped[datetime | None] = mapped_column(UTCDateTime)
    user_agent: Mapped[str] = mapped_column(String(255), nullable=False, default="")

    user: Mapped[User] = relationship()

    __table_args__ = (Index("ix_auth_sessions_user_id", "user_id"),)


class Project(Base, TimestampMixin):
    __tablename__ = "projects"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    #: The human readable id already used on disk, e.g. `beauty-centers-growth-01`.
    slug: Mapped[str] = mapped_column(String(120), unique=True, nullable=False)
    name: Mapped[str] = mapped_column(String(200), nullable=False)
    status: Mapped[str] = mapped_column(String(20), nullable=False, default="draft")
    storage_mode: Mapped[str] = mapped_column(String(20), nullable=False, default=MODE_WORKSPACE)
    canvas: Mapped[dict] = mapped_column(JsonColumn, nullable=False, default=dict)
    settings: Mapped[dict] = mapped_column(JsonColumn, nullable=False, default=dict)
    created_by: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("users.id", ondelete="SET NULL")
    )
    archived_at: Mapped[datetime | None] = mapped_column(UTCDateTime)

    memberships: Mapped[list[Membership]] = relationship(
        back_populates="project", cascade="all, delete-orphan"
    )
    documents: Mapped[list[Document]] = relationship(
        back_populates="project", cascade="all, delete-orphan"
    )

    __table_args__ = (
        CheckConstraint(
            "storage_mode in ('workspace', 'managed')", name="ck_projects_storage_mode"
        ),
        CheckConstraint(
            "status in ('draft', 'review', 'approved', 'published')", name="ck_projects_status"
        ),
    )


class Membership(Base, TimestampMixin):
    """Who can see and change a project, and with which role."""

    __tablename__ = "memberships"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    project_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    user_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    role: Mapped[str] = mapped_column(String(20), nullable=False, default=ROLE_VIEWER)

    project: Mapped[Project] = relationship(back_populates="memberships")
    user: Mapped[User] = relationship(back_populates="memberships")

    __table_args__ = (
        UniqueConstraint("project_id", "user_id", name="uq_memberships_project_user"),
        CheckConstraint("role in ('viewer', 'editor', 'owner')", name="ck_memberships_role"),
    )


class Document(Base, TimestampMixin):
    """Current state of one editorial JSON file.

    For a `managed` project `content` is authoritative. For a `workspace`
    project the file on disk is authoritative and this row keeps the metadata
    (etag, revision counter, last author) that the API needs.
    """

    __tablename__ = "documents"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    project_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    name: Mapped[str] = mapped_column(String(60), nullable=False)
    content: Mapped[dict | list | None] = mapped_column(JsonColumn)
    etag: Mapped[str] = mapped_column(String(64), nullable=False, default="")
    revision_number: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    updated_by: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("users.id", ondelete="SET NULL")
    )

    project: Mapped[Project] = relationship(back_populates="documents")

    __table_args__ = (UniqueConstraint("project_id", "name", name="uq_documents_project_name"),)


class Revision(Base):
    """An immutable snapshot of one document, created on every accepted write."""

    __tablename__ = "revisions"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    project_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    document_name: Mapped[str] = mapped_column(String(60), nullable=False)
    number: Mapped[int] = mapped_column(Integer, nullable=False)
    content: Mapped[dict | list] = mapped_column(JsonColumn, nullable=False)
    etag: Mapped[str] = mapped_column(String(64), nullable=False)
    parent_etag: Mapped[str | None] = mapped_column(String(64))
    message: Mapped[str] = mapped_column(String(500), nullable=False, default="")
    #: Set when this revision was produced by restoring an older one.
    restored_from: Mapped[str | None] = mapped_column(String(32))
    author_id: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("users.id", ondelete="SET NULL")
    )
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)

    __table_args__ = (
        UniqueConstraint(
            "project_id", "document_name", "number", name="uq_revisions_document_number"
        ),
        Index("ix_revisions_document", "project_id", "document_name"),
    )


class Asset(Base, TimestampMixin):
    """Metadata of one object in storage. The bytes never enter the database."""

    __tablename__ = "assets"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    project_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    key: Mapped[str] = mapped_column(String(512), nullable=False)
    #: raw, proxy, angle, audio, render, preview, font …
    kind: Mapped[str] = mapped_column(String(40), nullable=False, default="raw")
    content_type: Mapped[str] = mapped_column(String(120), nullable=False, default="")
    size: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    sha256: Mapped[str | None] = mapped_column(String(64))
    meta: Mapped[dict] = mapped_column(JsonColumn, nullable=False, default=dict)
    uploaded_by: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("users.id", ondelete="SET NULL")
    )

    __table_args__ = (UniqueConstraint("project_id", "key", name="uq_assets_project_key"),)


class RenderJob(Base, TimestampMixin):
    """Unit of work for the worker: proxy, transcription, render, quality gate."""

    __tablename__ = "render_jobs"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    project_id: Mapped[str] = mapped_column(
        String(32), ForeignKey("projects.id", ondelete="CASCADE"), nullable=False
    )
    kind: Mapped[str] = mapped_column(String(40), nullable=False, default="render")
    status: Mapped[str] = mapped_column(String(20), nullable=False, default=JOB_QUEUED)
    priority: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    max_attempts: Mapped[int] = mapped_column(Integer, nullable=False, default=3)
    payload: Mapped[dict] = mapped_column(JsonColumn, nullable=False, default=dict)
    result: Mapped[dict | None] = mapped_column(JsonColumn)
    error: Mapped[str | None] = mapped_column(Text)
    available_at: Mapped[datetime] = mapped_column(
        UTCDateTime, nullable=False, default=utcnow
    )
    started_at: Mapped[datetime | None] = mapped_column(UTCDateTime)
    finished_at: Mapped[datetime | None] = mapped_column(UTCDateTime)
    #: Name of the worker process currently holding the job.
    locked_by: Mapped[str | None] = mapped_column(String(120))
    locked_at: Mapped[datetime | None] = mapped_column(UTCDateTime)
    requested_by: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("users.id", ondelete="SET NULL")
    )

    __table_args__ = (
        CheckConstraint(
            "status in ('queued', 'running', 'succeeded', 'failed', 'cancelled')",
            name="ck_render_jobs_status",
        ),
        Index("ix_render_jobs_queue", "status", "available_at", "priority"),
    )


class AuditEvent(Base):
    """Append-only record of everything that changed a project."""

    __tablename__ = "audit_events"

    id: Mapped[str] = mapped_column(String(32), primary_key=True, default=new_id)
    project_id: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("projects.id", ondelete="CASCADE")
    )
    actor_id: Mapped[str | None] = mapped_column(
        String(32), ForeignKey("users.id", ondelete="SET NULL")
    )
    action: Mapped[str] = mapped_column(String(60), nullable=False)
    target: Mapped[str] = mapped_column(String(200), nullable=False, default="")
    data: Mapped[dict] = mapped_column(JsonColumn, nullable=False, default=dict)
    created_at: Mapped[datetime] = mapped_column(UTCDateTime, default=utcnow)

    __table_args__ = (Index("ix_audit_events_project", "project_id", "created_at"),)
